# The transport protocol to be used by the VPN session
# tcp | udp
protocol: udp

# creates a route and auth for the internet through the associated subnet
# true | false
route_to_internet: true

# if true split tunnel only pushes the routes on the vpn.
# if false the vpn will push a default which overwrites the client route table with the 
# entry 0.0.0.0/0 to route all traffic over the VPN.
# true | false
split_tunnel: false